baseURL = 'https://unballoon.github.io'
languageCode = 'pt-br'
title = 'UnBalloon'
theme = 'relearn'

canonifyURLs = false
relativeURLs = false
uglyURLs = false


defaultContentLanguage = "pt"

[outputs]
  # add JSON to the home to support lunr search; This is a mandatory setting
  # for the search functionality
  # add PRINT to home, section and page to activate the feature to print whole
  # chapters
  home = ["HTML", "RSS", "PRINT", "SEARCH"]
  section = ["HTML", "RSS", "PRINT"]
  page = ["HTML", "RSS", "PRINT"]
  chapters = ["HTML", "RSS", "PRINT"]

[params]
  uglyURLs = false # see uglyURLs setting above
  editURL = "https://github.com/UnBalloon/unballoon.github.io/edit/main/content/"
  description = "Repositorio do UnBalloon"
  author = "Bruno Vargas"
  showVisitedLinks = true
  collapsibleMenu = true
  disableBreadcrumb = false
  disableNextPrev = false
  disableLandingPageButton = false
  titleSeparator = "::"
  themeVariant = ["relearn-dark", "relearn-light", "neon", "learn", "blue", "green", "red" ]
  disableSeoHiddenPages = true
  # this is for the stylesheet generator to allow for interactivity in Mermaid
  # graphs; you usually will not need it and you should remove this for
  # security reasons
  mermaidInitialize = "{ \"securityLevel\": \"loose\" }"
  additionalContentLanguage = [ "pt" ]

  # disableLanguages = ['en']

[Languages]
  [Languages.pt]
    title = "UnBalloon"
    weight = 1
    languageName = "Portuguese"
    landingPageName = "<i class='fas fa-home'></i> Início"

  [[Languages.pt.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-github'></i> Repositório GitHub"
    identifier = "ds"
    url = "https://github.com/UnBalloon/unballoon.github.io"
    weight = 10
  
  [[Languages.pt.menu.shortcuts]]
  name = "<i class='fa fa-code'></i> CodeForces"
  url = "https://codeforces.com/group/nituVTsHQX"
  weight = 11

  [[Languages.pt.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-telegram'></i> Telegram"
    url = "https://t.me/unballoon"
    weight = 12
  
  [[Languages.pt.menu.shortcuts]]
    name = "<i class='fab fa-fw fa-discord'></i> Discord"
    url = "https://discord.gg/uc4htcV7fD"
    weight = 13
  

  [[Languages.pt.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-bullhorn'></i> Créditos"
    url = "more/credits/"
    weight = 30

  [[Languages.pt.menu.shortcuts]]
    name = "<i class='fas fa-fw fa-tags'></i> Tags"
    url = "tags/"
    weight = 40
